openapi: 3.0.0
info:
  title: VICTA API - Auth
  version: "1.0.0"
servers:
  - url: /api/v1
paths:
  /auth/register:
    post:
      summary: Регистрация пользователя
      operationId: register
      responses:
        "200":
          description: Успешная регистрация
          content:
            application/json:
              schema:
                $ref: "../components/api_response.yaml"
  /auth/login:
    post:
      summary: Вход в систему
      operationId: login
      responses:
        "200":
          description: Успешный вход
          content:
            application/json:
              schema:
                $ref: "../components/api_response.yaml"
