version: '3.1'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db:
