version: '3.8'

services:
  db:
    image: postgres:17
    restart: always
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data/

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "${API_PORT}:3000"
    volumes:
      - ./.env:/app/.env:ro

volumes:
  db:
