openapi: 3.0.0
info:
  title: VICTA API - Companies
  version: 1.0.0
servers:
  - url: /api/v1
paths:
  /auth/register:
    post:
      summary: Регистрация пользователя
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                company_id:
                  type: integer
                  nullable: true
              required:
                - email
                - password
      responses:
        '200':
          description: Успешная регистрация
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    description: 'Результат запроса. Может быть объектом, массивом и т.п.'
                  message:
                    type: string
                    description: Сообщение о результате операции
                  status:
                    type: integer
                    description: HTTP статус ответа
                required:
                  - data
                  - message
                  - status
  /auth/login:
    post:
      summary: Вход в систему
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Успешный вход
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    description: 'Результат запроса. Может быть объектом, массивом и т.п.'
                  message:
                    type: string
                    description: Сообщение о результате операции
                  status:
                    type: integer
                    description: HTTP статус ответа
                required:
                  - data
                  - message
                  - status
  /companies:
    post:
      summary: Создание компании
      operationId: createCompany
      security:
        - bearerAuth: [ ]
      responses:
        '200':
          description: Компания создана
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    description: 'Результат запроса. Может быть объектом, массивом и т.п.'
                  message:
                    type: string
                    description: Сообщение о результате операции
                  status:
                    type: integer
                    description: HTTP статус ответа
                required:
                  - data
                  - message
                  - status
    get:
      summary: Получение списка компаний
      operationId: getCompanies
      security:
        - bearerAuth: [ ]
      responses:
        '200':
          description: Список компаний
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    description: 'Результат запроса. Может быть объектом, массивом и т.п.'
                  message:
                    type: string
                    description: Сообщение о результате операции
                  status:
                    type: integer
                    description: HTTP статус ответа
                required:
                  - data
                  - message
                  - status
  '/companies/{id}':
    get:
      summary: Получение компании по id
      operationId: getCompany
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Данные компании
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    description: 'Результат запроса. Может быть объектом, массивом и т.п.'
                  message:
                    type: string
                    description: Сообщение о результате операции
                  status:
                    type: integer
                    description: HTTP статус ответа
                required:
                  - data
                  - message
                  - status
    put:
      summary: Обновление компании
      operationId: updateCompany
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Компания обновлена
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    description: 'Результат запроса. Может быть объектом, массивом и т.п.'
                  message:
                    type: string
                    description: Сообщение о результате операции
                  status:
                    type: integer
                    description: HTTP статус ответа
                required:
                  - data
                  - message
                  - status
    delete:
      summary: Удаление компании
      operationId: deleteCompany
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Компания удалена
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    description: 'Результат запроса. Может быть объектом, массивом и т.п.'
                  message:
                    type: string
                    description: Сообщение о результате операции
                  status:
                    type: integer
                    description: HTTP статус ответа
                required:
                  - data
                  - message
                  - status
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
