// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

// ApiResponse defines model for ApiResponse.
type ApiResponse struct {
	// Data Результат запроса. Может быть объектом, массивом и т.п.
	Data interface{} `json:"data"`

	// Message Сообщение о результате операции
	Message string `json:"message"`

	// Status HTTP статус ответа
	Status int `json:"status"`
}
