package victa_bot

type ChatState int

const (
	StateWaitingCreateCompanyName ChatState = iota
	StateWaitingUpdateCompanyName
	StateWaitingConfirmDeleteCompany
	StateWaitingConfirmDeleteUser
	StateWaitingConfirmDeleteApp
	StateWaitingUpdateCompanyIntegration
	StateWaitingCreateAppName
	StateWaitingCreateAppSlug
	StateWaitingUpdateAppName
	StateWaitingUpdateAppSlug
)
