// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// RemoveCompanyUsersJSONBody defines parameters for RemoveCompanyUsers.
type RemoveCompanyUsersJSONBody = []int

// AddCompanyUsersJSONBody defines parameters for AddCompanyUsers.
type AddCompanyUsersJSONBody = []int

// RemoveCompanyUsersJSONRequestBody defines body for RemoveCompanyUsers for application/json ContentType.
type RemoveCompanyUsersJSONRequestBody = RemoveCompanyUsersJSONBody

// AddCompanyUsersJSONRequestBody defines body for AddCompanyUsers for application/json ContentType.
type AddCompanyUsersJSONRequestBody = AddCompanyUsersJSONBody

// CompanyUsersServerInterface represents all server handlers.
type CompanyUsersServerInterface interface {
	// Удаление пользователей из компании
	// (DELETE /company-users/{id})
	RemoveCompanyUsers(c *gin.Context, id int)
	// Получение информации о пользователе компании
	// (GET /company-users/{id})
	GetCompanyUser(c *gin.Context, id int)
	// Добавление пользователей в компанию
	// (POST /company-users/{id})
	AddCompanyUsers(c *gin.Context, id int)
}

// CompanyUsersServerInterfaceWrapper converts contexts to parameters.
type CompanyUsersServerInterfaceWrapper struct {
	Handler            CompanyUsersServerInterface
	HandlerMiddlewares []CompanyUsersMiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type CompanyUsersMiddlewareFunc func(c *gin.Context)

// RemoveCompanyUsers operation middleware
func (siw *CompanyUsersServerInterfaceWrapper) RemoveCompanyUsers(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveCompanyUsers(c, id)
}

// GetCompanyUser operation middleware
func (siw *CompanyUsersServerInterfaceWrapper) GetCompanyUser(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCompanyUser(c, id)
}

// AddCompanyUsers operation middleware
func (siw *CompanyUsersServerInterfaceWrapper) AddCompanyUsers(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddCompanyUsers(c, id)
}

// CompanyUsersGinServerOptions provides options for the Gin server.
type CompanyUsersGinServerOptions struct {
	BaseURL      string
	Middlewares  []CompanyUsersMiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterCompanyUsersHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterCompanyUsersHandlers(router gin.IRouter, si CompanyUsersServerInterface) {
	RegisterCompanyUsersHandlersWithOptions(router, si, CompanyUsersGinServerOptions{})
}

// RegisterCompanyUsersHandlersWithOptions creates http.Handler with additional options
func RegisterCompanyUsersHandlersWithOptions(router gin.IRouter, si CompanyUsersServerInterface, options CompanyUsersGinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := CompanyUsersServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.DELETE(options.BaseURL+"/company-users/:id", wrapper.RemoveCompanyUsers)
	router.GET(options.BaseURL+"/company-users/:id", wrapper.GetCompanyUser)
	router.POST(options.BaseURL+"/company-users/:id", wrapper.AddCompanyUsers)
}
