package victa_bot

type ChatState int

const (
	StateWaitingCreateCompanyName ChatState = iota
	StateWaitingUpdateCompanyName
	StateWaitingConfirmDeleteCompany
	StateWaitingConfirmDeleteUser
	StateWaitingConfirmDeleteApp
	StateWaitingCreateAppName
	StateWaitingCreateAppSlug
	StateWaitingUpdateAppName
	StateWaitingUpdateAppSlug
	StateWaitingUpdateAppStoreURL
	StateWaitingUpdatePlayStoreURL
	StateWaitingUpdateRuStoreURL
	StateWaitingUpdateAppGalleryURL
	StateWaitingUpdateCodemagicApiKey
	StateWaitingUpdateNotificationBotToken
	StateWaitingUpdateDeployNotificationChatID
	StateWaitingUpdateErrorNotificationChatID
	StateWaitingUpdateIssueNotificationChatID
	StateWaitingUpdateVersionNotificationChatID
	StateWaitingUpdateReviewsNotificationChatID
	StateWaitingUploadGoogleJSON
	StateWaitingUploadAppleP8
	StateWaitingUpdateAppleKeyID
	StateWaitingUpdateAppleIssuerID
)
