package victa_bot

type ChatState int

const (
	StateWaitingCreateCompanyName ChatState = iota
	StateWaitingUpdateCompanyName
	StateWaitingConfirmDeleteCompany
	StateWaitingConfirmDeleteUser
	StateWaitingConfirmDeleteApp
	StateWaitingCreateAppName
	StateWaitingCreateAppSlug
	StateWaitingUpdateAppName
	StateWaitingUpdateAppSlug
	StateWaitingUpdateCodemagicApiKey
	StateWaitingUpdateNotificationBotToken
	StateWaitingUpdateDeployNotificationChatID
	StateWaitingUpdateErrorNotificationChatID
	StateWaitingUpdateIssueNotificationChatID
)
