name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env from secret
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          echo "$ENV_FILE" > .env

      - name: Prepare staging directory
        run: |
          mkdir staging
          rsync -a \
            --exclude='.git' \
            --exclude='victa.tar.gz' \
            --exclude='staging' \
            . staging/

      - name: Archive staging contents
        run: |
          tar czf victa.tar.gz -C staging .

      - name: Clean up staging
        run: rm -rf staging

      - name: Copy archive and deploy script to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          source: "victa.tar.gz,deploy.sh"
          target: "/opt/victa/releases/"

      - name: Run deploy script on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          script: |
            set -e
            cd /opt/victa
            mkdir -p releases
            cp releases/deploy.sh .
            bash deploy.sh
