name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create .env
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          echo "$ENV_FILE" > .env
      - name: Archive repository
        run: |
          tar czf victa.tar.gz --exclude='victa.tar.gz' --exclude='.git' .
        
      - name: Copy archive and deploy script to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          source: "victa.tar.gz,deploy.sh"
          target: "/opt/victa/releases/"

      - name: Run deploy script on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          script: |
            set -e
            # Переходим в корневую директорию приложения на сервере
            cd /opt/victa
            # Если ранее не была создана директория releases, создаем её
            mkdir -p releases
            # Перемещаем deploy.sh из releases (если он там) в корень, чтобы его можно было вызвать
            cp releases/deploy.sh .
            # Запускаем скрипт деплоя
            bash deploy.sh