name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Archive repository
        run: |
          mkdir artifacts
          tar czf artifacts/victa.tar.gz .

      - name: Copy archive and deploy script to server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          source: |
            victa.tar.gz
            deploy.sh
          target: "/opt/victa/releases/"

      - name: Run deploy script on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          script: |
            set -e
            # Переходим в корневую директорию приложения на сервере
            cd /opt/victa
            # Если ранее не была создана директория releases, создаем её
            mkdir -p releases
            # Перемещаем deploy.sh из releases (если он там) в корень, чтобы его можно было вызвать
            cp releases/deploy.sh .
            # Запускаем скрипт деплоя
            bash deploy.sh